# Generated by Django 4.1.5 on 2023-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCC',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='fcc_index')),
                ('Developer_Email_ID', models.EmailField(max_length=254, verbose_name='fcc_email')),
                ('Repo', models.CharField(max_length=20, verbose_name='fcc_Repo')),
                ('Last_Merge_Branch', models.CharField(max_length=20, verbose_name='fcc_merge_branch')),
                ('Open_PR', models.IntegerField(verbose_name='fcc_open_pr')),
                ('Merged_PR', models.IntegerField(verbose_name='fcc_close_pr')),
                ('Declined_PR', models.IntegerField(verbose_name='fcc_decline_pr')),
                ('Open_PR_DateTime', models.TextField(verbose_name='fcc open date time')),
                ('Close_PR_DateTime', models.TextField(verbose_name='fcc close date time')),
                ('Declined_PR_DateTime', models.TextField(verbose_name='fcc decline date time')),
                ('Ages_of_Open_PR', models.TextField()),
                ('Ages_of_Close_PR', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HmicSandBox',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='hmicsandbox_index')),
                ('Developer_Email_ID', models.EmailField(max_length=254, verbose_name='hmicsandbox_email')),
                ('Repo', models.CharField(max_length=20, verbose_name='hmicsandbox_Repo')),
                ('Last_Merge_Branch', models.CharField(max_length=20, verbose_name='hmicsandbox_merge_branch')),
                ('Open_PR', models.IntegerField(verbose_name='hmicsandbox_open_pr')),
                ('Merged_PR', models.IntegerField(verbose_name='hmicsandbox_close_pr')),
                ('Declined_PR', models.IntegerField(verbose_name='hmicsandbox_decline_pr')),
                ('Open_PR_DateTime', models.TextField(verbose_name='hmicsandbox open date time')),
                ('Close_PR_DateTime', models.TextField(verbose_name='hmicsandbox close date time')),
                ('Declined_PR_DateTime', models.TextField(verbose_name='hmicsandbox decline date time')),
                ('Ages_of_Open_PR', models.TextField()),
                ('Ages_of_Close_PR', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RCC',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='rcc_index')),
                ('Developer_Email_ID', models.EmailField(max_length=254, verbose_name='rcc_email')),
                ('Repo', models.CharField(max_length=20, verbose_name='rcc_Repo')),
                ('Last_Merge_Branch', models.CharField(max_length=20, verbose_name='rcc_merge_branch')),
                ('Open_PR', models.IntegerField(verbose_name='rcc_open_pr')),
                ('Merged_PR', models.IntegerField(verbose_name='rcc_close_pr')),
                ('Declined_PR', models.IntegerField(verbose_name='rcc_decline_pr')),
                ('Open_PR_DateTime', models.TextField(verbose_name='rcc open date time')),
                ('Close_PR_DateTime', models.TextField(verbose_name='rcc close date time')),
                ('Declined_PR_DateTime', models.TextField(verbose_name='rcc decline date time')),
                ('Ages_of_Open_PR', models.TextField()),
                ('Ages_of_Close_PR', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rtosapp',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='rtosapp_index')),
                ('Developer_Email_ID', models.EmailField(max_length=254, verbose_name='rtosapp_email')),
                ('Repo', models.CharField(max_length=20, verbose_name='rtosapp_Repo')),
                ('Last_Merge_Branch', models.CharField(max_length=20, verbose_name='rtosapp_merge_branch')),
                ('Open_PR', models.IntegerField(verbose_name='rtosapp_open_pr')),
                ('Merged_PR', models.IntegerField(verbose_name='rtosapp_close_pr')),
                ('Declined_PR', models.IntegerField(verbose_name='rtosapp_decline_pr')),
                ('Open_PR_DateTime', models.TextField(verbose_name='rtosapp open date time')),
                ('Close_PR_DateTime', models.TextField(verbose_name='rtosapp close date time')),
                ('Declined_PR_DateTime', models.TextField(verbose_name='rtosapp decline date time')),
                ('Ages_of_Open_PR', models.TextField()),
                ('Ages_of_Close_PR', models.TextField()),
            ],
        ),
    ]
