# Generated by Django 4.1.5 on 2023-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtosapps',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False, verbose_name='rtosapp_index')),
                ('Developer_Email_ID', models.EmailField(max_length=254, verbose_name='rtosapp_email')),
                ('Repo', models.CharField(max_length=20, verbose_name='rtosapp_Repo')),
                ('Last_Merge_Branch', models.CharField(max_length=20, verbose_name='rtosapp_merge_branch')),
                ('Open_PR', models.IntegerField(verbose_name='rtosapp_open_pr')),
                ('Merged_PR', models.IntegerField(verbose_name='rtosapp_close_pr')),
                ('Declined_PR', models.IntegerField(verbose_name='rtosapp_decline_pr')),
                ('Open_PR_DateTime', models.TextField(verbose_name='rtosapp open date time')),
                ('Close_PR_DateTime', models.TextField(verbose_name='rtosapp close date time')),
                ('Declined_PR_DateTime', models.TextField(verbose_name='rtosapp decline date time')),
                ('Ages_of_Open_PR', models.TextField()),
                ('Ages_of_Close_PR', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rtosapp',
        ),
    ]
