# Generated by Django 4.1.5 on 2023-03-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0003_all_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_repo',
            name='Close_PR_DateTime',
            field=models.TextField(verbose_name='repos close date time'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Declined_PR',
            field=models.IntegerField(verbose_name='repos_decline_pr'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Declined_PR_DateTime',
            field=models.TextField(verbose_name='repos decline date time'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Developer_Email_ID',
            field=models.EmailField(max_length=254, verbose_name='repos_email'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Last_Merge_Branch',
            field=models.CharField(max_length=20, verbose_name='repos_merge_branch'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Merged_PR',
            field=models.IntegerField(verbose_name='repos_close_pr'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Open_PR',
            field=models.IntegerField(verbose_name='repos_open_pr'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Open_PR_DateTime',
            field=models.TextField(verbose_name='repos open date time'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='Repo',
            field=models.CharField(max_length=20, verbose_name='repos_Repo'),
        ),
        migrations.AlterField(
            model_name='all_repo',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='repos_index'),
        ),
    ]
